export const BD_UNIVERSITIES = [
  "National University, Bangladesh (NU)",
  "University of Dhaka (DU)",
  "Bangladesh University of Engineering and Technology (BUET)",
  "Jahangirnagar University (JU)",
  "Rajshahi University (RU)",
  "Chittagong University (CU)",
  "Khulna University (KU)",
  "Shahjalal University of Science and Technology (SUST)",
  "Jagannath University (JnU)",
  "Rajshahi University of Engineering & Technology (RUET)",
  "Khulna University of Engineering & Technology (KUET)",
  "Chittagong University of Engineering & Technology (CUET)",
  "Dhaka University of Engineering & Technology (DUET)",
  "Bangladesh Agricultural University (BAU)",
  "North South University (NSU)",
  "BRAC University (BRACU)",
  "Independent University, Bangladesh (IUB)",
  "American International University-Bangladesh (AIUB)",
  "United International University (UIU)",
  "East West University (EWU)",
  "Daffodil International University (DIU)",
  "Ahsanullah University of Science and Technology (AUST)",
  "University of Liberal Arts Bangladesh (ULAB)",
  "International Islamic University Chittagong (IIUC)",
  "Southeast University (SEU)",
  "Green University of Bangladesh (GUB)",
  "Stamford University Bangladesh",
  "State University of Bangladesh",
  "City University",
  "World University Bangladesh",
  "Northern University Bangladesh",
  "Primeasia University",
  "Presidency University Bangladesh",
  "Bangladesh University of Professionals (BUP)",
  "Dhaka International University (DIU)",
  "University of Asia Pacific (UAP)",
  "University of Information Technology and Sciences (UITS)",
  "Uttara University",
  "Military Institute of Science and Technology (MIST)",
  "Pabna University of Science and Technology (PUST)",
  "Begum Rokeya University, Rangpur (BRUR)",
  "Comilla University (CoU)",
  "Jatiya Kabi Kazi Nazrul Islam University (JKKNIU)",
  "Gopalganj University of Science and Technology",
  "Maulana Bhashani Science and Technology University",
  "Sher-e-Bangla Agricultural University",
  "Port City International University",
  "International University of Scholars",
];
